server:
  port: 8050

spring:
  application:
    name: microservice-config-server

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/workspace/temp

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh