server:
  port: 8000
  tomcat:
    accesslog:
      enabled: true

spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql

  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    level: '[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n'