server:
  port: 8010

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example.cloud.feign.UserFeignClient: DEBUG

user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
